name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 4.0.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: 
  http: 
  crypto: 
  convert: 
  xml: 
  buffer: 
  intl: ^0.18.0
  mime: 
  path: 

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.2
  html: ^0.15.3
